CC := mipsel-linux-gcc
CFLAGS := `sdl-config --libs --cflags` -ggdb3 -O0 --std=c99 -Wall -lSDL_image -lm
HDRS :=
SRCS := src/main.c src/game.c src/graphics.c src/logic.c
OBJS := $(SRCS:.c=.o)

EXEC := 2048.dge

all: $(EXEC)

$(EXEC): $(OBJS) $(HDRS) Makefile
	$(CC) -o $@ $(OBJS) $(CFLAGS)
	cp ./2048.dge ./ipk/data/home/retrofw/games/2048/2048.dge
	cp -r assets ./ipk/data/home/retrofw/games/2048/assets/
	./ipk/create-ipk.sh

clean:
	rm -f $(EXEC) $(OBJS)

.PHONY: all clean
